### ISSUE TITLE
Dummy Dump verarbeiten

### ISSUE THREAD

**Issue by foxx08** [INFB-Projekt/flashspeicher-rekonstruktion#3]
**Beschreibung**

Datenformat spezifizieren

**Akzeptanzkriterien**
- [x] Erstelle/Suche  Dummy Dump z.B. (:.salt)
- [x] Dokumentiere Aufbereitung des Datenformats 

**Update**
 - [x] @FiscPete: Bin CSV in HEX übersetzen (HEX should be in pandas dataframe)
 - [ ] @almunc: HEX filtern auf multi- und single-block writes (write out as CSV)
 - [ ] @Batuhan-Oezcan: CRCs und responses prüfen (Tobi will continue in same file)
 - [x] @STRG-C-Coder: gefilterte HEX CSV schreiben

**Comment by almunc** [comment]
https://docs.google.com/document/d/1EpC5SbD_qsYf018sDTxGHAgxgwvCuG1mUFT0MomC0bo/edit?usp=sharing

**Comment by foxx08** [comment]
> https://docs.google.com/document/d/1EpC5SbD_qsYf018sDTxGHAgxgwvCuG1mUFT0MomC0bo/edit?usp=sharing

Fragen ans Handware-Team sowie zu den Anforderungen am 17.04. klären und entsprechend notieren. Im Anschluss wird die Doku dann ins Wiki übertragen.

**Comment by almunc** [comment]
Aufteilung:
 - Peter: Bin CSV in HEX übersetzen (HEX should be in pandas dataframe)
 - Alex: HEX filtern auf multi- und single-block writes (write out as CSV)
 - Bathuan: CRCs und responses prüfen (Tobi will continue in same file)
 - Tobi M.: gefilterte HEX CSV schreiben

**Comment by foxx08** [comment]
geblockt: #9
