### ISSUE TITLE
Image Vorbereitung

### ISSUE THREAD

**Issue by foxx08** [INFB-Projekt/flashspeicher-rekonstruktion#8]
**Beschreibung**

**Akzeptanzkriterien**
- [x] Image mounten
- [x] Output vergleichen

**Comment by TobiGit11** [comment]
- image mountbar mit "sudo mount -o loop,offset=4194304 -t vfat sdCardImage.img /mnt/point" wobei offset spezifisch für sdcard ist
- Outputdatein die gleichen wie auf der scCard
